CAMERA_WIDTH = 1920
CAMERA_HEIGHT = 1080
CAMERA_FPS = 20
CAMERA_RESOLUTION_FALLBACKS = (
    (1920, 1080),
)
WINDOWS_PREFERRED_CAMERA_INDEX = 1
CAMERA_SCAN_MAX_INDEX = 3

# O perfil da câmera é fixo em 1920x1080 a 20 FPS. O sistema ainda pode trocar
# apenas o backend ou o formato de captura para recuperar o fluxo, mas nunca
# altera a resolução nem o FPS definidos para a operação.
FRAME_INTERVAL_MS = 50
PARAMETERIZATION_PREVIEW_INTERVAL_MS = 50
OPERATION_PREVIEW_WIDTH = 480
OPERATION_PREVIEW_HEIGHT = 270
OPERATION_PREVIEW_INTERVAL_MS = 50
OPERATION_RESULT_DISPLAY_MS = 3000
GPIO_TRIGGER_BCM_PIN = 27
GPIO_TRIGGER_BOUNCE_S = 0.08
GPIO_EVENT_POLL_MS = 50
GPIO_POSITIONING_DELAY_MS = 2000
